networks:
  eventpulse-net:
    external: true

services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    networks:
      - eventpulse-net
    ports:
      - "9092:9092" # Kafka API
      - "9644:9644" # Admin API
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      # LISTENERS
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,INSIDE://0.0.0.0:29092
      # ADVERTISED (what clients should use)
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092,INSIDE://redpanda:29092
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    networks:
      - eventpulse-net
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda

  redpanda-init:
    image: redpandadata/redpanda:latest
    networks:
      - eventpulse-net
    depends_on:
      - redpanda
    entrypoint: ["/bin/sh", "-c"]
    command:
      # Wait for broker to be ready
      - |
        echo "Waiting for Redpanda..."
        until rpk cluster info --brokers=redpanda:29092 >/dev/null 2>&1; do
          sleep 1
        done

        echo "Creating topics..."
        rpk topic create events -X brokers=redpanda:29092 || true
        rpk topic create logs -X brokers=redpanda:29092 || true
        rpk topic create metrics -X brokers=redpanda:29092 || true

        echo "Kafka topics created âœ”"

volumes:
  redpanda-data:
